title:              devesigner의 기술블로그
email:              devehoper@daum.net
description:        이것저것하는 개발자
author:             Start Bootstrap
baseurl:            ""
url:                "https://devesigner.github.io"

# Social Profiles
github_username:    devesigner
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
disqus_shortname: 'devesigner'