title:              devesigner의 기술블로그
email:              devehoper@daum.net
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            ""
url:                "https://devesigner.github.io"

# Social Profiles
twitter_username:   devesigner
github_username:    devehoper
facebook_username:  devesigner
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
