title:              Clean Blog
email:              devehoper@daum.net
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://devesign.github.io"

# Social Profiles
twitter_username:   devesign
github_username:    devesign
facebook_username:  devesign
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
